package modele;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tournee.java
//  @ Date : 05/11/2015
//  @ Author : 
//
//




public class Tournee {
	public Object id;
	public Object date;
	public void getDate() {
	
	}
	
	public void setDate() {
	
	}
	
	public void rechercherTournee() {
	
	}
	
	public void triTourneeDate() {
	
	}
}
